### ISSUE TITLE
passing `jello` params?

### ISSUE THREAD

**Issue by lovetoburnswhen** [kellyjonbrazil/jellex#1]
eg for deeply nested fields I'd use `jello -s`
Is there any way to do this with `jellex`?

**Comment by kellyjonbrazil** [comment]
I hadn’t thought about outputting anything other than JSON in the viewer window, but it might be possible to display the schema view there and then add the schema argument to the jello command on exit. I’ll take a look into it. Thanks for the suggestion!

**Comment by kellyjonbrazil** [comment]
I added a Schema viewer window in v0.5.0, now available via `pip`. I wasn't able to figure out how to toggle the window on and off just yet. Maybe in a future version!
