### ISSUE TITLE
Feature Request - Schema View toggle

### ISSUE THREAD

**Issue by SikhNerd** [kellyjonbrazil/jellex#2]
It would be really nice to have a toggle that horizontally splits the viewer pane, and in the new pane display the output of `jello -s`

**Comment by kellyjonbrazil** [comment]
That sounds like a good idea! I'll take a look at that.

**Comment by kellyjonbrazil** [comment]
I added a Schema viewer window in v0.5.0, now available via `pip`. I wasn't able to figure out how to toggle the window on and off just yet. Maybe in a future version!
