### ISSUE TITLE
Starting jellex gives: RuntimeError: no running event loop

### ISSUE THREAD

**Issue by RenHoekNL** [kellyjonbrazil/jellex#8]
I installed jellex via pip. jello runs fine. I get this:

> jellex 1.json
> Traceback (most recent call last):
>   File "/home/keymaster/.local/bin/jellex", line 5, in <module>
>     from jellex.cli import main
>   File "/home/keymaster/.local/lib/python3.10/site-packages/jellex/cli.py", line 231, in <module>
>     query.insert_text('_')
>   File "/home/keymaster/.local/lib/python3.10/site-packages/prompt_toolkit/buffer.py", line 1269, in insert_text
>     get_app().create_background_task(self._async_completer())
>   File "/home/keymaster/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 1057, in create_background_task
>     loop = self.loop or get_running_loop()
> RuntimeError: no running event loop
> sys:1: RuntimeWarning: coroutine 'Buffer._create_completer_coroutine.<locals>.async_completer' was never awaited

$ uname -a
Linux zabbix 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ python --version
Python 3.10.4

**Comment by kellyjonbrazil** [comment]
Thank you for reporting this! It looks like the latest version of one of the dependent libraries (prompt-toolkit) is causing the issue. You can downgrade prompt-toolkit to the previous version, which seems to work ok:
```
pip install pip install prompt-toolkit==3.0.36
```
In the mean-time I'll need to hardcode that version in the setup file.

**Comment by RenHoekNL** [comment]
Downgrading prompt-toolkit works.

**Comment by kellyjonbrazil** [comment]
I have hardcoded the requirements in jellex v0.5.7
